In [1]:
import numpy as np

# Crear dos matrices 1000x1000
A = np.random.rand(1000, 1000)
B = np.random.rand(1000, 1000)

# Multiplicación de matrices
C = np.dot(A, B)
# o también:
# C = A @ B

print(C)


[[243.82416605 256.96531021 244.16136136 ... 255.86600102 243.45586139
  253.28139393]
 [246.88644124 245.73476885 240.89006829 ... 244.97737671 237.73644908
  248.16964152]
 [258.06493416 253.99185146 251.21121104 ... 253.56089391 244.61928258
  259.9224773 ]
 ...
 [252.59112582 249.92097974 246.64297658 ... 243.51375195 243.07360336
  251.55525438]
 [255.16128404 253.78881492 256.50541177 ... 251.73031529 252.57664921
  256.76552228]
 [257.46184126 257.05554149 249.26976605 ... 250.36024582 244.05473556
  258.53359905]]


In [2]:
lista = [0,1,2,3,4]
array_1d = np.array(lista)

type(array_1d)

numpy.ndarray

In [3]:
array_1d

array([0, 1, 2, 3, 4])

In [4]:
lista = [0,1,2,3,4]
array_1d = np.array(lista)
array_1d + 2

array([2, 3, 4, 5, 6])

In [5]:
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr2d_f = np.array(list2, dtype='float')
arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [7]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])